- core/src/pipeless_ai/lib/input/input.py
- core/src/pipeless_ai/lib/logger.py
- core/src/pipeless_ai/lib/output/output.py
- core/src/pipeless_ai/lib/worker/worker.py
Update logger to show the component producing the log.
Fixes #3
> Show components in logs

- core/src/pipeless_ai/lib/input/input.py
- core/src/pipeless_ai/lib/output/output.py
- core/src/pipeless_ai/lib/worker/worker.py
This PR adds log info as well.
Fixes #5
> Fix: Premature end of stream

- core/src/pipeless_ai/lib/input/input.py
Use GLib mainloop as in the rest of the code.
> Fix Mainloop type

- README.md
- core/src/pipeless_ai/lib/config.py
- core/src/pipeless_ai/lib/input/input.py
Implement webcam support as requested in #12
> feat: Add webcam support

- core/pyproject.toml
- core/src/pipeless_ai/lib/connection.py
- core/src/pipeless_ai/lib/input/input.py
- core/src/pipeless_ai/lib/worker/worker.py
- package/Dockerfile
- package/README.md
- package/docker-compose.yaml
- package/scripts/entrypoint.sh
- package/scripts/libpipeless.sh
- package/scripts/python-nonroot.sh
This PR adds the required files and logic to create container images for pipeless.
It also fixes a bug related to the `InputOutputSocket` which was set to listen on the wrong component.
Finally, it adds a new socket type that allows the input to know when the first worker is ready to set the pipeline to the playing state.
> Add pipeless container image

- .github/workflows/docker-publish.yaml
This PR adds a new workflow to publish the container image to DockerHub
> feat(package): Add container publishing action

- README.md
- core/src/pipeless_ai/lib/output/output.py
This PR adds support for `RTMP` as output protocol.
> feat(core): Add RTMP support

- core/src/pipeless_ai/lib/config.py
- core/src/pipeless_ai/lib/input/input.py
- core/src/pipeless_ai/lib/output/output.py
- core/src/pipeless_ai/lib/worker/worker.py
This PR allows to disable video output. Useful when you just want to export data to a messaging broker or event streaming platform.
> feat(core): Allow to disable video output

- README.md
- core/README.md
- core/poetry.lock
- core/pyproject.toml
- core/src/pipeless_ai/core.py
- core/src/pipeless_ai/lib/app/app.py
- core/src/pipeless_ai/lib/config.py
- core/src/pipeless_ai/lib/worker/inference/runtime.py
- core/src/pipeless_ai/lib/worker/inference/utils.py
- core/src/pipeless_ai/lib/worker/worker.py
- plugins/draw/plugin.py
This PR includes in the core the ONNX Runtime to allow the execution of models automatically. It includes several features with it like automatically detect required transformations to minimize the pre-processing that the user has to implement as well as chaining pre-processing models automatically.
Inference execution with any model out of the box
> feat(core): Add built-in Onnx Runtime to run inference

- core/src/pipeless_ai/lib/app/app.py
- core/src/pipeless_ai/lib/config.py
- core/src/pipeless_ai/lib/worker/worker.py
> feat(worker): Add automatic line profiler for user code

- cli/src/pipeless_ai_cli/commands/run.py
- cli/src/pipeless_ai_cli/commands/templates/default/app.py
- core/src/pipeless_ai/lib/config.py
This PR removes the need of providing a config file. This is very useful when configuring only with env vars.
- fixes #
> feat(config): Do not require config file

- cli/pyproject.toml
> Bump CLI version

- README.md
Add new badge to the README
- fixes #
> Add link to discord community

- cli/src/pipeless_ai_cli/commands/run.py
- core/src/pipeless_ai/lib/worker/worker.py
This PR allows a user to split the Pipeless application into different files and import functions from `app.py`
- fixes #
> feat(imports): Support user module imports

- core/src/pipeless_ai/lib/connection.py
- core/src/pipeless_ai/lib/worker/worker.py
Sometimes the worker ready message was lost. With this change we ensure it always arrives to the input.
- fixes #
> fix(worker): Ensure ready message arrives

- core/src/pipeless_ai/core.py
- core/src/pipeless_ai/lib/plugins.py
This PR runs `n_workers` workers when using `pipeless run`
- fixes #
> feat(workers): Allow to run several workers when using the run command locally

- package/helm-chart/pipeless/Chart.yaml
- package/helm-chart/pipeless/values.yaml
Minor fixes/improvements in the Helm chart
> Minor fixes/improvements in the Helm chart

- core/pyproject.toml
- core/src/pipeless_ai/lib/worker/worker.py
> fix(worker): Fix missing class attribute initialization

- examples/cats/pre-process.py
- examples/yolo/init.py
- install.sh
This PR updates the install script to build from source when there are no pre-built binaries.
It also adds guidance to the user on how to install required dependencies.
Finally, it removes the requirement of root provileges to install
- fixes #
> Update install script

- pipeless/Cargo.lock
- pipeless/Cargo.toml
- pipeless/src/cli/streams.rs
- pipeless/src/config/adapters/rest.rs
- pipeless/src/config/streams.rs
- pipeless/src/main.rs
This PR adds `remove` and `update` stream commands to the CLI.
- fixes #
> Add update and remove stream commands

- install.sh
> feat(install): Add flag to force build from source

- .github/workflows/docker-publish.yaml
- install.sh
- package/Dockerfile
- package/Dockerfile-cuda
- package/Dockerfile-tensorrt
- package/scripts/entrypoint.sh
- package/scripts/install-nonroot.sh
- package/scripts/libcargo.sh
- package/scripts/libpipeless.sh
- package/scripts/postunpack.sh
This PR updates the containers to use Pipeless version 1.0
- fixes #
> Update containers to Pipeless version 1.0

- README.md
> Update README video

- pipeless/Cargo.lock
- pipeless/Cargo.toml
- pipeless/src/config/streams.rs
- pipeless/src/dispatcher.rs
Fix issue removing managers and unassigning pipelines
- fixes #70
> fix: Remove managers and unassign pipelines properly

- examples/yolo/post-process.py
- examples/yolo/process.py
This PR implements a simple use case of the new KV store in the YOLO example to automatically skip frames processing and produce a fluid stream even in limited hardware. 
- fixes #
> feat(examples): Allow skip frames in the YOLO example

- install.sh
Improve how the recommended command to install gstreamer is shown
- fixes #
> fix(install): Improve recommended install commands

- README.md
Add a new section to the README pointing to the benchmark
- fixes #
> feat(readme): Add benchmark section

- pipeless/src/input/pipeline.rs
This PR allows the input pipeline to read from NVMM memory. The change is provisional, since we should not move out from NVMM memory to SystemMemory
Allows to use Pipeless in Nvidia Jetson devices
> feat: Support for nvmm in input pipeline

- pipeless/src/stages/parser.rs
This PR adds support for stateful hooks to the parser, so users can easily indicate when a hook should maintain state.
> feat(parser): Add support for stateful hooks

- pipeless/Cargo.lock
- pipeless/Cargo.toml
- pipeless/src/output/pipeline.rs
> fix: Fix RTMP output

- README.md
> Add live demo link to README.md

- install.sh
> fix(install): Update bug report link

- pipeless/Cargo.lock
- pipeless/Cargo.toml
- pipeless/src/cli/streams.rs
- pipeless/src/config/streams.rs
This PR fixes the issues of the table shown when there are several streams on it. We replace `json_to_table` by `tabled` here.
- fixes #
> fix: Improve table from list streams command

- pipeless/Cargo.lock
- pipeless/Cargo.toml
- pipeless/src/config/adapters/rest.rs
This PR includes the whole data of the created stream on the response, including the stream id
- fixes #
> fix(api): Include stream id in POST response

- .github/workflows/pipeless-build-and-release.yaml
This PR adds support to release Linux ARM64 from a self hosted Jetson runner
- fixes #
> Add Jetson job in self hosted runner

- pipeless/Cargo.lock
- pipeless/Cargo.toml
> fix: New version to release Linux arm64 binaries

- pipeless/Cargo.lock
- pipeless/Cargo.toml
- pipeless/src/cli/start.rs
- pipeless/src/output/pipeline.rs
This PR includes a few minor fixes to improve the user experience.
* Logs a debug message instead of error when an output pad is EOS after the end of a stream.
* Handles CTRL+C properly to exit.
- fixes #
> Minor fixes to improve UX

- README.md
- install.sh
- package/scripts/libpipeless.sh
This PR adds support for Linux ARM container images
- fixes #
> feat(container): Support Linux ARM image

- examples/onnx-yolo/post-process.py
- examples/onnx-yolo/pre-process.py
- examples/yolo/process.py
This PR makes some changes to improve the YOLOv8 ONNX example
- fixes #
> fix(examples): Improve yolo onnx example
