pipeless-ai/pipeless

core/src/pipeless_ai/core.py, core/src/pipeless_ai/lib/config.py, core/src/pipeless_ai/lib/input/input.py, core/src/pipeless_ai/lib/output/output.py, core/src/pipeless_ai/lib/worker/worker.py
By loading the configuration on each component we avoid errors on Mac OS and Windows due to the different process forking method.
Fixes #8
=> Load configuration on each component individually

core/src/pipeless_ai/lib/input/input.py, core/src/pipeless_ai/lib/output/output.py, core/src/pipeless_ai/lib/worker/worker.py
Using a local sink output and leaving the process running can be confusing. 
This patch 
- Finishes the execution early in such case
- Adds additional feedback to the user to improve usability.
=> feat: close stream on file output

core/poetry.lock, core/pyproject.toml
Require NumPy under `1.25.0` to support Debian with remote sources like `https`.
Fixes: #14
=> fix: Downgrade NumPy requirement

README.md, core/src/pipeless_ai/lib/input/input.py, core/src/pipeless_ai/lib/output/output.py, core/src/pipeless_ai/lib/worker/worker.py
This PR allows Pipeless to process any number of consecutive streams when using remote input and outputs. In this case Pipeless will never stop, and it will process any stream that appears on the remote URI.
=> feat(core): Allow processing consecutive streams

README.md, cli/pyproject.toml, cli/src/pipeless_ai_cli/commands/templates/default/README.md, cli/src/pipeless_ai_cli/commands/templates/default/app.py, core/pyproject.toml, core/src/pipeless_ai/lib/app/app.py, examples/cats/README.md, examples/cats/app.py, examples/cats/config.yaml, examples/kafka/README.md, examples/kafka/app.py, examples/pose/README.md, examples/pose/app.py, examples/pose/config.yaml, examples/text-overlay/app.py, examples/text-overlay/config.yaml, plugins/src/pipeless_ai_plugins/kafka/README.md
The context was producing confusion between the users, so this PR gets rid of it since the same can be achieved via class variables.
=> feat(core,cli): Replace context by class variables

core/src/pipeless_ai/lib/input/input.py, core/src/pipeless_ai/lib/worker/worker.py
This PR loads the plugins before the worker loop, making the `__init__` to be executed just once when loading the plugin, ideal for download stuff or performing actions to setup the plugins and the `before` to be executed before every stream.
It also handles user application errors to show them on the screen.
=> feat(core): Load plugins before worker is ready

cli/src/pipeless_ai_cli/commands/run.py
This PR makes the CLI to check the existence of the user `app.py` only when using the worker, since input and output do not require it. 
- fixes #
=> fix(cli): Load user application only in the worker

README.md, core/poetry.lock, core/pyproject.toml, core/src/pipeless_ai/lib/worker/inference/runtime.py, core/src/pipeless_ai/lib/worker/inference/utils.py, core/src/pipeless_ai/lib/worker/worker.py
This PR allows installing Pipeless on different flavors for ONNX CPU and ONNX GPU separatedly. This is required because the onnx dependencies are released as `onnxruntime` and `onnxruntime-gpu` and they are not compatible
- fixes #
=> feat(core): Create ONNX flavors

pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/data.rs, pipeless/src/input/pipeline.rs, pipeless/src/kvs/mod.rs, pipeless/src/kvs/store.rs, pipeless/src/lib.rs, pipeless/src/stages/languages/python.rs
This PR adds a KV store that can be used to share data between frames.
The user can call `pipeless_kvs_set` and `pipeless_kvs_get` to set and get KV pairs.
The internal keys are automatically converted to the format `stage_name:pipeline_id:user_key` to avoid conflicts when running multiple streams and multiple stages per stream.
Finally, the `pipeless_kvs_get` function will return an empty value by default, including when the key does not exist. Since frames are executed in parallel, a key could not exist at the time of getting it, users need to take this into account.
The `pipeless_kvs_set` function converts any value to string before inserting it into the store.
- fixes #71
=> feat(kv_store): Add KV store

pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/data.rs
The dynamic arrays for `inference_input` and `inference_output` were initialized with a single element with a zero, not allowing to check if the array is empty from a hook.
This PR changes that to initialize them without any values (`[]`)
Allows user hooks to check if the `inference_input` and/or `inference_output` arrays are empty.
- fixes #
=> fix(frame): Initialize dynamic arrays empty instead of with zeros

examples/yolo/process.py, pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/data.rs, pipeless/src/input/pipeline.rs, pipeless/src/stages/languages/python.rs
This PR fixes the value set in the input timestamps to properly represent the epoch seconds.
Also, it simplifies the skip frames logic in the yolo example from using the KV store to just compare the timestamp and the input FPS.
- fixes #
=> fix(data): Set epoch seconds in frame input_ts

pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/config/adapters/rest.rs, pipeless/src/config/video.rs, pipeless/src/data.rs, pipeless/src/dispatcher.rs, pipeless/src/gst/utils.rs, pipeless/src/input/pipeline.rs, pipeless/src/kvs/store.rs, pipeless/src/output/pipeline.rs, pipeless/src/pipeline.rs, pipeless/src/stages/languages/python.rs
This PR improves error handling by avoiding the use of `panic` and `expect`  during streams processing. This avoids Pipeless to crash on an error, showing the error and continuing with the processing of any other possible stream.
This is specially necessary for production deployment.
- fixes #
=> fix: Improve error handling

pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/cli/start.rs, pipeless/src/events.rs, pipeless/src/pipeline.rs, pipeless/src/stages/hook.rs, pipeless/src/stages/inference/hook.rs, pipeless/src/stages/inference/onnx.rs, pipeless/src/stages/languages/python.rs, pipeless/src/stages/languages/rust.rs, pipeless/src/stages/parser.rs, pipeless/src/stages/path.rs, pipeless/src/stages/stage.rs
This PR performs a refactor of the path executor in order to fix the bottleneck that was preventing parallel execution. 
- fixes #89
- fixes #85
=> Fix bottleneck in path executor

pipeless/src/data.rs, pipeless/src/gst/utils.rs, pipeless/src/output/pipeline.rs, pipeless/src/stages/languages/python.rs, pipeless/src/stages/path.rs
=> Fix: Minor code improvements

pipeless/src/config/adapters/rest.rs
Listening in `127.0.0.1` does not allow for external connections while `0.0.0.0`does.
- fixes #
=> fix(rest api): listen in 0.0.0.0 by default

pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/cli/streams.rs, pipeless/src/config/adapters/rest.rs, pipeless/src/config/streams.rs, pipeless/src/dispatcher.rs, pipeless/src/main.rs, pipeless/src/pipeline.rs, pipeless/src/stages/hook.rs
This PR adds support for the `restart_policy` option. The restart policy allows to specify when the processing of a stream should be restarted, including `error`, `eos`, `never` or `always`. 
- fixes #
=> feat: Add stream restart policy

pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/dispatcher.rs, pipeless/src/kvs/store.rs, pipeless/src/stages/languages/python.rs
This PR takes care of cleaning up the KV store when a stream ends. The cleanup was missing in previous versions.
- fixes #
=> fix: cleanup KV store when pipeline ends

pipeless/src/config/streams.rs
Fix restart loop when using multistreams and stages that contain `-` in the name 
- fixes #111
=> fix: stream hash differs  when stage includes '-'

pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/pipeline.rs
Providing an empty output URI was producing a pipeline error. This PR fixes it.
- fixes #
=> fix: Bug with output empty URI

pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/config/video.rs, pipeless/src/input/pipeline.rs
This PR adds support for selecting the device when using `v4l2` in the form `v4l2:/dev/videoX`. For example: `--input-uri v4l2:/dev/video0`
- fixes #117
=> feat: Allow source camera selection

pipeless/src/config/streams.rs
This PR removes the restriction of using unique input URIs. There is no real reason for not allow duplicated URIs and sometimes it is even required if you want to process the same stream with two different execution paths
- fixes #
=> Allow duplicated input URIs

package/Dockerfile-tensorrt
The TensorRT image was using a base image with CUDA 12, producing an error because the ONNX runtime was unable to find the CUDA 11 libraries. This PR fixes the problem by using a base image that ships CUDA 11.7, which is also consistent with the CUDA container image.
- fixes https://github.com/pipeless-ai/pipeless/discussions/124
=> fix(container): Use base image with CUDA 11.7 for TensorRT

pipeless/src/stages/inference/onnx.rs, pipeless/src/stages/inference/session.rs
This PR adds support for custom operation libraries for the onnx runtime
- fixes #
=> feat(onnxruntime): Support custom op library

pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/cli/start.rs, pipeless/src/dispatcher.rs, pipeless/src/event_exporters/events.rs, pipeless/src/event_exporters/mod.rs, pipeless/src/lib.rs, pipeless/src/main.rs, pipeless/src/pipeline.rs, pipeless/src/stages/path.rs
This PR adds support to export stream events to Redis.
It includes the CLI flag `--export-events-redis` to enable the export and requires the configuration of the Redis URL and channel via `PIPELESS_REDIS_URL` and `PIPELESS_REDIS_CHANNEL` env vars.
=> feat: Add redis event exporter

.github/workflows/docker-publish.yaml
The CUDA runner was failling to build images because it was running out of space. This PR adds a first step to the workflow to remove some big packages to increase the build space on the runner.
- fixes #
=> fix(workflows): Increase build space in CUDA runner

examples/object-tracking/init.py, examples/object-tracking/process.py, examples/yolo/post-process.py, pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/data.rs, pipeless/src/input/pipeline.rs, pipeless/src/stages/hook.rs, pipeless/src/stages/languages/python.rs
This PR adds support for sequential sorted processing in stateful hooks. This allows implementing use cases that make use of hooks that preserve state and require sorted frame processing. A trivial example is object tracking.
- fixes #
=> feat(hook): Support sequential sorted execution

pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/cli/start.rs, pipeless/src/dispatcher.rs, pipeless/src/events.rs, pipeless/src/input/pipeline.rs, pipeless/src/main.rs, pipeless/src/output/pipeline.rs, pipeless/src/pipeline.rs
This PR adds support to limit the processing buffer per stream. This allows for discarding frames when the performance decreases maintaining the processing in real-time even when resources are low. 
- fixes #
=> feat(core): Add backpressure mechanism

examples/onnx-candy/post-process.py, examples/onnx-yolo/post-process.py, examples/yolo-world/post-process.py, examples/yolo-world/pre-process.py, examples/yolo-world/process.json, pipeless/Cargo.lock, pipeless/Cargo.toml, pipeless/src/data.rs, pipeless/src/events.rs, pipeless/src/stages/inference/onnx.rs, pipeless/src/stages/languages/python.rs
This PR adds support for several inference outputs when using the ONNX Runtime.
It also adds a new example with the YOLO World model
Users using the ONNX runtime will need to update their code to obtain the specific output from the `inference_output` dict 
- fixes #
=> Support several inference outputs for ONNX Runtime + YOLO World example
